[package]
name = "terminal_size"
version = "0.4.4"
description = "Gets the size of your Linux or Windows terminal"
documentation = "https://docs.rs/terminal_size"
repository = "https://github.com/eminence/terminal-size"
keywords = ["terminal", "console", "term", "size", "dimensions"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.63.0"

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"
targets = [
    "aarch64-apple-darwin",
    "aarch64-pc-windows-msvc",
    "aarch64-unknown-linux-gnu",
    "i686-pc-windows-msvc",
    "i686-unknown-linux-gnu",
    "x86_64-pc-windows-gnu",
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
]

[target.'cfg(all(unix, not(any(target_os = "espidf", target_os = "horizon", target_os = "vita"))))'.dependencies]
rustix = { version = "1.1.2", features = ["termios"] }

[target.'cfg(windows)'.dependencies.windows-sys]
version = ">=0.52, <0.62"
features = [
    "Win32_Foundation",
    "Win32_System_Console",
]

[features]
default = ["unsupported"]
# This feature is used to build the crate on unsupported platforms.
# You can disable this feature if you want compilation to fail on unsupported platforms.
unsupported = []
