name: CI
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        toolchain: [1.63.0, stable, beta, nightly]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Generate lockfile
        if: matrix.toolchain != '1.63.0'
        run: cargo generate-lockfile
      - name: Generate lockfile (minimal-versions)
        if: matrix.toolchain == '1.63.0'
        run: cargo generate-lockfile -Z minimal-versions
        env:
          RUSTC_BOOTSTRAP: 1
      - name: Cargo build
        run: cargo build --locked

  cross:
    name: Cross
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [1.63.0, stable, beta, nightly]
        target: [aarch64-linux-android, i686-unknown-linux-gnu]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install toolchain and targets
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: ${{ matrix.target }}
      - name: Generate lockfile
        if: matrix.toolchain != '1.63.0'
        run: cargo generate-lockfile
      - name: Generate lockfile (minimal-versions)
        if: matrix.toolchain == '1.63.0'
        run: cargo generate-lockfile -Z minimal-versions
        env:
          RUSTC_BOOTSTRAP: 1
      - name: Cargo check (${{ matrix.target }})
        run: cargo check --target ${{ matrix.target }} --locked

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        toolchain: [1.63.0, stable, beta, nightly]
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install faketty
        run: cargo install faketty
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Generate lockfile
        if: matrix.toolchain != '1.63.0'
        run: cargo generate-lockfile
      - name: Generate lockfile (minimal-versions)
        if: matrix.toolchain == '1.63.0'
        run: cargo generate-lockfile -Z minimal-versions
        env:
          RUSTC_BOOTSTRAP: 1
      - name: Cargo test (under faketty)
        env:
          TERMINAL_SIZE_TEST_REQUIRE_TTY: "1"
        run: faketty cargo test --locked -- --nocapture
